### ISSUE TITLE
PageExtractor

### ISSUE THREAD

**Issue by to-uni-hh** [talbx/wiki-science#1]
Wir benötigen ein MapReduce Job, um die Pages aus dem XML zu extrahieren.

**Comment by tdicknet** [comment]
Schwieriger als gedacht, da MapReduce so komplex. XML ist doof. -> branch page_extractor läuft aktuell im Hadoop leider noch nicht, weil der XMLPageInputType noch nich korrekt implementiert ist. Hier fehlt wahrscheinlich auch noch was in der Klassensignatur: extends bla oder ein anderes interface, da initialize noch nicht aufgerufen wird...

**Comment by talbx** [comment]
@tdicknet auf dem feature branch ist jetzt das projekt etwas runter gestripped, weil hadoop mit spring servlets nicht arbeiten kann; kann ich auch morgen im detail nochmal erzählen. 

Der Mapper für Pages hatte zahlreiche Exceptions geworfen zur laufzeit, ich konnte einige fixxen aber noch läuft es nicht auf hadoop, vielleicht findest du das problem morgen / heut nacht im code. nicht wundern - in unserem userverzeichnis finden sich dutzende jars mit zwischenständen die ich getestet habe
