### ISSUE TITLE
Setup Project

### ISSUE THREAD

**Issue by talbx** [talbx/wiki-science#2]
nach update auf master →

tools:

- [ ] java 13

- [ ]  maven

Dann sollte bei jedem mit mvn clean install / mvn clean install -DskipTests das Projekt durchlaufen. 

Mit mvn spring-boot:run sollte das Programm startbar sein lokal (auch wenn exceptions dann fliegen ist das nur auf das fehlende hadoop cluster zurückzuführen)

**Comment by talbx** [comment]
nach update auf master →

tools:

- [ ] java 13
- [ ] maven

Dann sollte bei jedem mit mvn clean install / mvn clean install -DskipTests das Projekt durchlaufen. 

Mit mvn spring-boot:run sollte das Programm startbar sein lokal (auch wenn exceptions dann fliegen ist das nur auf das fehlende hadoop cluster zurückzuführen)

**Comment by to-uni-hh** [comment]
Jupp, läuft local thx. im hadoop gibts böse fehler😂😂




Get Outlook for Android







On Tue, Feb 18, 2020 at 11:44 PM +0100, "talbx" <notifications@github.com> wrote:












nach update auf master →



tools:



 java 13

[ ] maven





Dann sollte bei jedem mit mvn clean install / mvn clean install -DskipTests das Projekt durchlaufen.



Mit mvn spring-boot:run sollte das Programm startbar sein lokal (auch wenn exceptions dann fliegen ist das nur auf das fehlende hadoop cluster zurückzuführen)
